# 1. URL de Conexão (Endereço do banco nutri_app)
spring.datasource.url=jdbc:mysql://localhost:3306/nutri_app?createDatabaseIfNotExist=true&serverTimezone=UTC

# 2. Usuário padrão do MySQL
spring.datasource.username=root

# 3. Senha do seu MySQL (A mesma do Workbench)
spring.datasource.password=root

# 4. Driver de conexão
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 5. Estratégia de criação de tabelas (O Java cria as tabelas para você)
spring.jpa.hibernate.ddl-auto=update

# 6. Mostrar o SQL no console (Para sabermos se ele está criando as tabelas)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true