spring.application.name=nutriapp

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/nutri_app?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Serializa datas como string
spring.jackson.serialization.write-dates-as-timestamps=false

# PORTA
server.port=8080

# GROQ — cole sua chave aqui
groq.api.key=${GROQ_API_KEY}